/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'David' at '3/10/16 11:22 PM' with Gradle 2.11
 *
 * @author David, @date 3/10/16 11:22 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
